name: Dependabot config file
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Set reviewers for pull requests
    reviewers:
      - "clownai"
    # Group all updates together
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest"
          - "nodemon"
          - "ts-node"
          - "typescript"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "jest"
          - "nodemon"
          - "ts-node"
          - "typescript"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow up to 5 pull requests for security updates
    security-updates-limit: 5
    # Specify version update strategy
    versioning-strategy: increase
